version: '3'
services:
  mapgen-frontend:
    build:
      context: . 
      dockerfile: ./container/frontend/Dockerfile
    image: ghcr.io/xcsoar/mapgen-frontend
    ports: 
      - "9090:9090"
    volumes:
      - mapgen-jobs:/opt/mapgen/jobs
  mapgen-worker:
    build:
      context: . 
      dockerfile: ./container/worker/Dockerfile
    image: ghcr.io/xcsoar/mapgen-worker
    volumes:
      - mapgen-jobs:/opt/mapgen/jobs
      - mapgen-data:/opt/mapgen/data

volumes:
  mapgen-data:
  mapgen-jobs:
